on: push
name: Publish Website
jobs:
  web-deploy:
    name: Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: Get Latest Code
      uses: prem-modi-website/demodata@v1
      with:  
        server: github.com
#         username: admin@thebestbeta.com
#         password: DdxA{[)NaFd#
    - name: Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        server: ftp.thebestbeta.com
        username: admin@thebestbeta.com
        password: DdxA{[)NaFd#
