name: Publish Website to CPanel
on:
  push:
    branches:
      - master
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@demodata
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: prem-modi-website/demodata@v1.0.0
      with:
        server: ftp.thebestbeta.com
        username: admin@thebestbeta.com
        password: DdxA{[)NaFd#
