on: push
name: Main-Data
jobs:
  web-deploy:
    name: Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Main-Data
      uses: github/main-data@v4.9.5
      with:
        server: ftp.thebestbeta.com
        username: admin@thebestbeta.com
        password: DdxA{[)NaFd#
