on: push
name: Publish Website
jobs:
  web-deploy:
    name: Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: Get Latest Code
      uses: actions/checkout@v2
      
    - name: Main-Data
      uses: github/main-data@v1.0.0
      with:
        server: ftp.thebestbeta.com
        username: admin@thebestbeta.com
        password: DdxA{[)NaFd#
